// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdwsjrcs-N-7JHtBT9h4IU5jPpk2WSRvI',
    appId: '1:888751353465:web:fde536df8dbb2cf2d2eea8',
    messagingSenderId: '888751353465',
    projectId: 'campus-connect-d794f',
    authDomain: 'campus-connect-d794f.firebaseapp.com',
    storageBucket: 'campus-connect-d794f.firebasestorage.app',
    measurementId: 'G-E8DDZYNMGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-p1vmK3pJ_TMK0MVcCw-s3fyNsZ6WaaE',
    appId: '1:888751353465:android:3b5202a2aa9cf34ad2eea8',
    messagingSenderId: '888751353465',
    projectId: 'campus-connect-d794f',
    storageBucket: 'campus-connect-d794f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzC2IuleGE3VEiqH5sC3QBncp4EuakH6c',
    appId: '1:888751353465:ios:8692a84f33a15ee7d2eea8',
    messagingSenderId: '888751353465',
    projectId: 'campus-connect-d794f',
    storageBucket: 'campus-connect-d794f.firebasestorage.app',
    iosClientId: '888751353465-f6vqd0vl49k2c0792rhh26fga3utibo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzC2IuleGE3VEiqH5sC3QBncp4EuakH6c',
    appId: '1:888751353465:ios:8692a84f33a15ee7d2eea8',
    messagingSenderId: '888751353465',
    projectId: 'campus-connect-d794f',
    storageBucket: 'campus-connect-d794f.firebasestorage.app',
    iosClientId: '888751353465-f6vqd0vl49k2c0792rhh26fga3utibo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdwsjrcs-N-7JHtBT9h4IU5jPpk2WSRvI',
    appId: '1:888751353465:web:0cfc3adcb3b37eb0d2eea8',
    messagingSenderId: '888751353465',
    projectId: 'campus-connect-d794f',
    authDomain: 'campus-connect-d794f.firebaseapp.com',
    storageBucket: 'campus-connect-d794f.firebasestorage.app',
    measurementId: 'G-FL8VD87YK7',
  );

}